### ISSUE TITLE
Complex generic union type still not works

### ISSUE THREAD

**Issue by dimonchelli-dev** [Ne4to/N.SourceGenerators.UnionTypes#23]
Work:
```
public record Wrapped<TItem>(TItem Item);

[UnionType(typeof(int))]
[UnionType(typeof(Wrapped<string>))]
public partial class Result1
{
}

[UnionType(typeof(int))]
[UnionType(typeof(Wrapped<string>))]
[UnionConverterFrom(typeof(Result1))]
public partial class Result2
{
}
```

But if you use more complex type it not works:
```
public record Wrapped<TItem>(TItem Item);

[UnionType(typeof(int))]
[UnionType(typeof(Wrapped<IReadOnlyList<string>>))]
public partial class Result1
{
}

[UnionType(typeof(int))]
[UnionType(typeof(Wrapped<IReadOnlyList<string>>))]
[UnionConverterFrom(typeof(Result1))]
public partial class Result2
{
}
```
with error 
`'Result1.IsWrappedOfIReadOnlyList<>(string, _wrappedOfIReadOnlyList<string>)' must declare a body because it is not marked abstract, extern, or partial` and others
![image](https://github.com/Ne4to/N.SourceGenerators.UnionTypes/assets/89530799/183b68fc-5ca5-4aa8-89b5-faa23914327e)

**Comment by Ne4to** [comment]
fixed in [v0.22.0](https://www.nuget.org/packages/N.SourceGenerators.UnionTypes/0.22.0)
