### ISSUE TITLE
Unnnecessary boxing and unboxing for structs

### ISSUE THREAD

**Issue by virzak** [Ne4to/N.SourceGenerators.UnionTypes#7]
Imagine you want to combine structs:

```c#
public record struct SuccessStruct(int Value);

public record struct ValidationErrorStruct(int ErrorCode);

public record struct NotFoundErrorStruct;

[UnionType(typeof(SuccessStruct))]
[UnionType(typeof(ValidationErrorStruct))]
[UnionType(typeof(NotFoundErrorStruct))]
public partial struct FooStructResult
{
}
```

Could you use [this mechanism](https://github.com/dotnet/csharplang/discussions/1554#discussioncomment-98917) to avoid boxing / unboxing?

**Comment by Ne4to** [comment]
I've added a benchmark into `benchmark` branch. Here are [results](https://github.com/Ne4to/N.SourceGenerators.UnionTypes/blob/benchmark/src/N.SourceGenerators.UnionTypes.Benchmark/README.md). It shows no memory allocations but better mean time, so it is worth implementing anyway. It's possible this benchmark is not accurate for all scenarios so feel free to add more details.

**Comment by Ne4to** [comment]
It was supported in v0.15.0.  
Explicit StructLayout is used when container type is struct and all variants are structs.
